// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv2o9Go5280TdDAycTtjW9RrJmOIMJhrs',
    appId: '1:663820884208:web:ddd5e6a6dc2f913fb8ca35',
    messagingSenderId: '663820884208',
    projectId: 'attendance-app-2-1d1cb',
    authDomain: 'attendance-app-2-1d1cb.firebaseapp.com',
    storageBucket: 'attendance-app-2-1d1cb.firebasestorage.app',
    measurementId: 'G-S3GL0DFNK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF8qfLT6PzPR4t2nWt7CeFEZkwKWPew8w',
    appId: '1:663820884208:android:7a47f21e09a699e5b8ca35',
    messagingSenderId: '663820884208',
    projectId: 'attendance-app-2-1d1cb',
    storageBucket: 'attendance-app-2-1d1cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXy0c3u0uNaOuiQN6nBAgWNbHb6fEsuN8',
    appId: '1:663820884208:ios:29aa2f16b4b71d34b8ca35',
    messagingSenderId: '663820884208',
    projectId: 'attendance-app-2-1d1cb',
    storageBucket: 'attendance-app-2-1d1cb.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp2',
  );

}